### PR TITLE
Add @cjermain as maintainer

### PR DESCRIPTION
**Pull request by melund**

### CODE REVIEW

**Comment by cjermain** [comment]
It looks like build #4.2 needs to be restarted on TravisCI (restart button is on the build page). I've had this problem before with TravisCI, where it hangs without any errors and reports as failed.

**Comment by melund** [comment]
I would have merged it anyway. But I am on holiday and github does not allow merging builds that fail from a phone. @ddale could do it from a PC. Anyway I managed to restart the build.

**Comment by melund** [comment]
Ah. Found a workaround and merged it anyway...

**Comment by cjermain** [comment]
Awesome, thanks @melund! Sorry to interrupt your vacation!

**Comment by jakirkham** [comment]
Soon (within the next day) you should get an email that invites you to join conda-forge, @cjermain. Once accepted you will be added to a team with the same name as this recipe. Those will give you permissions on the feedstock (repo) for this recipe.

Make sure when proposing any change that you go through the typical GitHub workflow of forking the feedstock and making changes in your fork that you PR back. Once merged CIs will build and deploy any changes you make. Please let us know if you have any questions and welcome to conda-forge.

**Comment by cjermain** [comment]
Thanks @jakirkham!

**Pull request merged**
