### PR TITLE
Release version 0.4.3

### PR DESCRIPTION
**Pull request by cjermain**

### CODE REVIEW

**Comment by jakirkham** [comment]
Please also add `license_file: LICENSE.txt` to the `about` section.

**Comment by jakirkham** [comment]
Also please [re-render]( https://github.com/conda-forge/conda-smithy#re-rendering-an-existing-feedstock ) with `conda-smithy` 2.2.2.

**Comment by cjermain** [comment]
@jakirkham, thanks for the suggestions. This is still failing because `conda-smithy` changed the Python versions up from 3.4/3.5 to 3.5/3.6, while not all of the dependency packages are up to 3.6 version.

**Comment by jakirkham** [comment]
So Python 3.4 is no longer supported in conda-forge. Sorry CI limitations what they are we have to drop it.

That said, if this is not ready for Python 3.6, please add `skip: true  # [py>35]` to your `build` section and re-render. That will drop Python 3.4, but not yet add Python 3.6. Once your dependencies exist on Python 3.6, you can drop the `skip` and re-render to add Python 3.6 support.

**Comment by cjermain** [comment]
@jakirkham, I understand. It seems like the main bottleneck for CI is Appveyor at this point.

Once we get conda-forge/pyvisa-feedstock#6, I'll update this to 3.5/3.6.

**Pull request merged**
